services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8080" 
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - ORIGIN_ALLOWLIST=${ORIGIN_ALLOWLIST}
    networks:
      - app-network
    volumes:
      - ./internal/database/forum.db:/app/internal/database/forum.db

  frontend:
    build:
      context: ./web  
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
